-- 코드를 작성해주세요
WITH RANK_RESULT AS 
(SELECT RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING, ID, SIZE_OF_COLONY
FROM ECOLI_DATA),
COUNT_RESULT AS (SELECT COUNT(*) AS COUNT FROM ECOLI_DATA)
SELECT ID, 
    (CASE 
            WHEN (RANKING / COUNT)*100 <= 25 THEN 'CRITICAL'
            WHEN (RANKING / COUNT)*100 <= 50 THEN 'HIGH'
            WHEN (RANKING / COUNT)*100 <= 75 THEN 'MEDIUM'
            ELSE 'LOW'
    END) AS COLONY_NAME
FROM RANK_RESULT, COUNT_RESULT
ORDER BY ID ASC
