-- 코드를 작성해주세요
WITH MAX_VALUE AS (
SELECT ID, YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS COLONY_SIZE
FROM ECOLI_DATA
GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, b.COLONY_SIZE - a.SIZE_OF_COLONY AS YEAR_DEV, a.ID
FROM ECOLI_DATA a
LEFT JOIN MAX_VALUE b ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC