-- 코드를 작성해주세요
WITH val AS (SELECT COUNT_VALUE
FROM (
    SELECT 
            FISH_NAME,
            COUNT(*) OVER (PARTITION BY FISH_NAME) AS COUNT_VALUE
    FROM FISH_INFO
    LEFT JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
) AS a
GROUP BY FISH_NAME
HAVING FISH_NAME IN ('BASS', 'SNAPPER'))
SELECT SUM(COUNT_VALUE) AS FISH_COUNT
FROM val